#### GET
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJ2b2lkIiwiZW1haWwiOiJ2b2lkQHNwYWNlLm9yZyIsImlhdCI6MTcxODA3MTk3MiwiZXhwIjoxNzE4MDcxOTkyfQ.9bdL5h99IiwmWQdtG9f8mW-6LKbzIozEXLOiURCdF4c

#### Register
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "void",
    "email": "void@space.org",
    "password": "123456",
    "confPassword": "123456"
}

#### Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "void@space.org",
    "password": "123456"
}

#### Refresh Token
GET http://localhost:5000/token

#### Logout
DELETE http://localhost:5000/logout